/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://oe5osjjdpfc7jozdbahovk26wi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-grilu4pepzfnvhfosw5sdqmzwi",
    "aws_cognito_identity_pool_id": "us-east-2:e7922afb-824b-44db-b798-df2f77653d54",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SdBz8VHXe",
    "aws_user_pools_web_client_id": "2apjnusv1sv4r3peeidnb8dvgp",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "icc-florida-walletcard-storage-f94b11b7122414-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
